name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Connect to Prod AKS
        run: az aks get-credentials --resource-group sit722-rg --name sit722-aks-prod

      - name: Deploy to Prod
        run: kubectl apply -f k8s/
